### PR TITLE
Clean up containers and etcd data on stop

### PR DESCRIPTION
**Pull request by YungSang**
It makes machines re-usable for others or to deploy units again.

### CODE REVIEW

**Comment by polvi** [comment]
@YungSang the --rm should be handling that, no?

**Comment by YungSang** [comment]
@polvi Oops, you're right. I thought that I might see some containers remain on failure.

I will check it again.

**Comment by YungSang** [comment]
It was my mistake obviously. Closing...

**Comment by YungSang** [comment]
I'm sorry about that.

I re-open it to remove unnecessary 'docker rm' in redis-dyn-amb.service.

**Comment by polvi** [comment]
Thanks.

**Pull request merged**
